server:
  port: 9202
spring:
  boot:
    admin:
      client:
        url: http://localhost:9020
  application:
    name: service-bookings
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookingsBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
